apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-nodejs-app
  labels:
    app: devops-nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-nodejs-app
  template:
    metadata:
      labels:
        app: devops-nodejs-app
    spec:
      containers:
        - name: devops-nodejs-app
          image: 635054837309.dkr.ecr.us-east-1.amazonaws.com/devops-nodejs-app:43440a76b01e9863c1a67db46d7e000a6d01b8b5
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"